[package]
name = "corex"
version = "0.1.0"
edition = "2021"

[lib]
name = "corex"
path = "src/lib.rs"
test = true
doctest = true
doc = true
crate-type = ["lib"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
